name: CIT Crossdock

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  crossdock:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    strategy:
      matrix:
        steps:
        - name: crossdock
          cmd: bash scripts/build-crossdock.sh
    name: ${{ matrix.steps.name }}
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - uses: actions/setup-go@v3
      with:
        go-version: ^1.16

    - name: Export BRANCH variable
      uses: ./.github/actions/setup-branch

    - name: Install tools
      run: make install-ci
    
    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build, test, and publish ${{ matrix.steps.name }} image
      run: ${{ matrix.steps.cmd }}
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: Output crossdock logs
      run: make crossdock-logs
      if: ${{ failure() }}
