name: CIT Cassandra

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cassandra:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: actions/setup-go@v3
      with:
        go-version: ^1.16

    - name: Run cassandra integration tests
      run: bash scripts/cassandra-integration-test.sh
